import {
    accounts,
    accountsRelations,
    invitations,
    invitationsRelations,
    members,
    membersRelations,
    organizations,
    organizationsRelations,
    sessions,
    sessionsRelations,
    users,
    usersRelations,
    verifications,
} from './auth-schema';

export const schema = {
    users,
    sessions,
    accounts,
    verifications,
    organizations,
    members,
    invitations,
    usersRelations,
    sessionsRelations,
    accountsRelations,
    organizationsRelations,
    membersRelations,
    invitationsRelations,
};
